image: alpine/edge
tasks:
  - install-rust: |
      sudo apk add --no-cache rust cargo rust-clippy
  - test: |
      cd fiche-rs
      cargo test
  - lint: |
      cd fiche-rs
      cargo clippy --all -- -D clippy::all -D warning
