image: alpine/edge
tasks:
  - install-rust: |
      curl -proto '=https' -tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source "$HOME/.cargo/env"
      rustup default stable
      rustup component add clippy
  - test: |
      cd fiche-rs
      cargo test
  - lint: |
      cd fiche-rs
      cargo clippy --all -- -D clippy::all -D warnings
