image: alpine/edge
tasks:
  - install-rust: |
      curl -proto '=https' -tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source "$HOME/.cargo/env"
      rustup default stable
      rustup component add clippy
      cargo install cargo-tarpaulin
  - test: |
      source "$HOME/.cargo/env"
      cd fiche-rs
      cargo tarpaulin
  - lint: |
      source "$HOME/.cargo/env"
      cd fiche-rs
      cargo clippy --all -- -D clippy::all -D warnings
