image: alpine/edge
tasks:
  - install-openssl: |
      sudo apk add --no-cache openssl-dev
  - install-rust: |
      curl -L --proto '=https' -tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source "$HOME/.cargo/env"
      rustup default stable
      rustup component add clippy
      curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | sh
      cargo binstall -y --force cargo-tarpaulin
  - codecov: |
      export CODECOV_TOKEN="$(cat ~/codecov_token)"
      curl -Os https://uploader.codecov.io/latest/alpine/codecov
      chmod +x codecov
      ./codecov
  - test: |
      source "$HOME/.cargo/env"
      cd fiche-rs
      cargo tarpaulin
  - lint: |
      source "$HOME/.cargo/env"
      cd fiche-rs
      cargo clippy --all -- -D clippy::all -D warnings
