[package]
name = "fiche-rs"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
users = "0.11"
rand = "0.8"
libc = "0.2"
clap = { version = "4.4", features = ["derive"] }